"""remove unwanted tables and implement field in summaries table

Revision ID: 49031bc27aa6
Revises: 7849105ca36b
Create Date: 2025-11-23 12:25:03.216843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '49031bc27aa6'
down_revision: Union[str, Sequence[str], None] = '7849105ca36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('download_url', sa.String(length=200), nullable=True))
    op.drop_column('summaries', 'summary_text')
    op.drop_column('summaries', 'generated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('generated_by', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('summaries', sa.Column('summary_text', mysql.TEXT(), nullable=False))
    op.drop_column('summaries', 'download_url')
    # ### end Alembic commands ###
