"""implement model for argument scores

Revision ID: 737d00ba785c
Revises: f75fbba957a7
Create Date: 2025-11-21 10:47:11.915914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '737d00ba785c'
down_revision: Union[str, Sequence[str], None] = 'f75fbba957a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_argument_civility_analysis_id'), table_name='argument_civility_analysis')
    op.drop_table('argument_civility_analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('argument_civility_analysis',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('argument_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('toxicity_score', mysql.FLOAT(), nullable=False),
    sa.Column('civility_score', mysql.FLOAT(), nullable=False),
    sa.Column('flags', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['argument_id'], ['arguments.id'], name=op.f('argument_civility_analysis_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_argument_civility_analysis_id'), 'argument_civility_analysis', ['id'], unique=False)
    # ### end Alembic commands ###
