"""add consensus table

Revision ID: 7849105ca36b
Revises: 822c3a4f0c1d
Create Date: 2025-11-22 16:42:01.859747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7849105ca36b'
down_revision: Union[str, Sequence[str], None] = '822c3a4f0c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consensus_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debate_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consensus_recommendations_debate_id'), 'consensus_recommendations', ['debate_id'], unique=False)
    op.create_index(op.f('ix_consensus_recommendations_id'), 'consensus_recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consensus_recommendations_id'), table_name='consensus_recommendations')
    op.drop_index(op.f('ix_consensus_recommendations_debate_id'), table_name='consensus_recommendations')
    op.drop_table('consensus_recommendations')
    # ### end Alembic commands ###
